// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
	site: 'https://rufatmalikov.com',
	vite: {
		server: {
			allowedHosts: ['host.docker.internal'],
		},
	},
	redirects: {
		// Root redirects to the default locale's homepage.
		// Browsers that send Accept-Language could be auto-routed in middleware later if desired.
		'/': '/en/',
	},
	integrations: [
		starlight({
			routeMiddleware: './src/starlightRouteData.ts',
			title: {
				en: 'Rufat Malikov',
				az: 'Rüfət Məlikov',
			},
			description: 'QA automation enthusiast and educator. Playwright training, engineering writing, and side projects.',
			customCss: ['./src/styles/brand.css'],
			head: [
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
				},
				{
					tag: 'link',
					attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
				},
				{
					tag: 'link',
					attrs: {
						rel: 'stylesheet',
						href: 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500..600&family=Inter:wght@400;500;600;700&display=swap',
					},
				},
			],
			defaultLocale: 'en',
			locales: {
				en: { label: 'English', lang: 'en' },
				az: { label: 'Azərbaycan dili', lang: 'az' },
			},
			social: [
				{ icon: 'youtube', label: 'YouTube', href: 'https://www.youtube.com/@AIwithRufat' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/in/rufat-malikov-295aab22' },
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/TesterBaku' },
			],
			sidebar: [
				{
					label: 'Course',
					translations: { az: 'Kurs' },
					items: [{ autogenerate: { directory: 'course' } }],
				},
				{
					// Explicit per-module groups so the module headings can be localized
					// in Azerbaijani (Starlight cannot localize autogenerated folder labels).
					// In EN these groups autogenerate nothing (lessons are AZ-only) and would
					// otherwise render empty; the route middleware (src/starlightRouteData.ts)
					// prunes empty groups + the AZ-only glossary link so the EN sidebar shows
					// only the Overview stub.
					label: 'Python',
					translations: { az: 'Python Dərsləri' },
					items: [
						{ label: 'Overview', translations: { az: 'Giriş' }, link: '/python/' },
						{
							label: '00 — Start here',
							translations: { az: '00 — Başlanğıc' },
							items: [{ autogenerate: { directory: 'python/00-baslangic' } }],
						},
						{
							label: '01 — Talk to Python',
							translations: { az: '01 — Python ilə danış' },
							items: [{ autogenerate: { directory: 'python/01-python-ile-danis' } }],
						},
						{
							label: '02 — Make decisions',
							translations: { az: '02 — Qərar ver' },
							items: [{ autogenerate: { directory: 'python/02-qerar-ver' } }],
						},
						{
							label: '03 — Repeat',
							translations: { az: '03 — Təkrarla' },
							items: [{ autogenerate: { directory: 'python/03-tekrarla' } }],
						},
						{
							label: '04 — Collections',
							translations: { az: '04 — Kolleksiyalar' },
							items: [{ autogenerate: { directory: 'python/04-kolleksiyalar' } }],
						},
						{
							label: '05 — Functions',
							translations: { az: '05 — Funksiyalar' },
							items: [{ autogenerate: { directory: 'python/05-funksiyalar' } }],
						},
						{
							label: '06 — Projects',
							translations: { az: '06 — Layihə missiyaları' },
							items: [{ autogenerate: { directory: 'python/06-layihe-missiyalari' } }],
						},
						{ label: 'Glossary', translations: { az: 'Sözlük' }, link: '/python/sozluk/' },
					],
				},
				{
					label: 'BrauzerLab',
					items: [{ autogenerate: { directory: 'playwright' } }],
				},
				{
					label: 'Exam Helper',
					translations: { az: 'İmtahan Köməkçisi' },
					items: [{ autogenerate: { directory: 'exam-helper' } }],
				},
				{
					label: 'Projects',
					items: [{ autogenerate: { directory: 'projects' } }],
				},
				{ label: 'About', link: '/about/', translations: { az: 'Haqqında' } },
			],
			// Edit-this-page links — wire up once the repo is on GitHub.
			// editLink: { baseUrl: 'https://github.com/<user>/<repo>/edit/main/' },
		}),
		sitemap({
			// /python-demo/ is an internal M1 verification page — keep it out of the sitemap.
			filter: (page) => !page.includes('/python-demo'),
		}),
	],
});
