// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
	site: 'https://rufatmalikov.com',
	vite: {
		server: {
			allowedHosts: ['host.docker.internal'],
		},
	},
	redirects: {
		// Root redirects to the default locale's homepage.
		// Browsers that send Accept-Language could be auto-routed in middleware later if desired.
		'/': '/en/',
	},
	integrations: [
		starlight({
			routeMiddleware: './src/starlightRouteData.ts',
			title: {
				en: 'Rufat Malikov',
				az: 'Rüfət Məlikov',
			},
			description: 'QA automation enthusiast and educator. Playwright training, engineering writing, and side projects.',
			// Fonts are self-hosted via @fontsource-variable (bundled below), so there
			// is no render-blocking cross-origin Google Fonts request. fontsource CSS
			// comes first so the @font-face rules are defined before brand.css uses them.
			customCss: [
				'@fontsource-variable/fraunces/index.css',
				'@fontsource-variable/inter/index.css',
				'./src/styles/brand.css',
			],
			defaultLocale: 'en',
			locales: {
				en: { label: 'English', lang: 'en' },
				az: { label: 'Azərbaycan dili', lang: 'az' },
			},
			social: [
				{ icon: 'youtube', label: 'YouTube', href: 'https://www.youtube.com/@AIwithRufat' },
				{ icon: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/in/rufat-malikov-295aab22' },
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/TesterBaku' },
			],
			sidebar: [
				{
					// Explicit module links (not autogenerate) so the 14 flat module files
					// can be grouped into collapsible difficulty phases. Phases start
					// collapsed; Starlight auto-expands the one holding the active page.
					label: 'Course',
					translations: { az: 'Kurs' },
					items: [
						{ label: 'Overview', translations: { az: 'İcmal' }, link: '/course/' },
						{ label: '0 — Roadmap & setup', translations: { az: '0 — Kurs xəritəsi və quraşdırma' }, link: '/course/module-0/' },
						{
							label: 'Fundamentals',
							translations: { az: 'Əsaslar' },
							collapsed: true,
							items: [
								{ label: '1 — JS/TS for QA', translations: { az: '1 — QA üçün JS/TS' }, link: '/course/module-1/' },
								{ label: '2 — Mastering locators', translations: { az: '2 — Lokatorlar ustası' }, link: '/course/module-2/' },
								{ label: '3 — Actions & interactions', translations: { az: '3 — Əməliyyatlar və interaksiya' }, link: '/course/module-3/' },
								{ label: '4 — Assertions', translations: { az: '4 — İddialar' }, link: '/course/module-4/' },
							],
						},
						{
							label: 'Intermediate',
							translations: { az: 'Orta səviyyə' },
							collapsed: true,
							items: [
								{ label: '5 — Auto-waiting & flaky tests', translations: { az: '5 — Avtomatik gözləmə və flaky testlər' }, link: '/course/module-5/' },
								{ label: '6 — Test runner & config', translations: { az: '6 — Test icraçısı və konfiqurasiya' }, link: '/course/module-6/' },
								{ label: '7 — Page Object Model', translations: { az: '7 — Səhifə Obyekt Modeli (POM)' }, link: '/course/module-7/' },
								{ label: '8 — Fixtures & test data', translations: { az: '8 — Fixtures və test məlumatları' }, link: '/course/module-8/' },
								{ label: '9 — API testing & networking', translations: { az: '9 — API testi və şəbəkə' }, link: '/course/module-9/' },
							],
						},
						{
							label: 'Advanced',
							translations: { az: 'Qabaqcıl' },
							collapsed: true,
							items: [
								{ label: '10 — Auth & storage state', translations: { az: '10 — Auth və saxlama vəziyyəti' }, link: '/course/module-10/' },
								{ label: '11 — Visual / Mobile / A11y', translations: { az: '11 — Vizual / Mobil / Əlçatımlılıq' }, link: '/course/module-11/' },
								{ label: '12 — CI, Docker, reports', translations: { az: '12 — CI, Docker, hesabatlar' }, link: '/course/module-12/' },
								{ label: '13 — Final project review', translations: { az: '13 — Yekun layihə icmalı' }, link: '/course/module-13/' },
							],
						},
					],
				},
				{
					// Explicit per-module groups so the module headings can be localized
					// in Azerbaijani (Starlight cannot localize autogenerated folder labels).
					// In EN these groups autogenerate nothing (lessons are AZ-only) and would
					// otherwise render empty; the route middleware (src/starlightRouteData.ts)
					// prunes empty groups + the AZ-only glossary link so the EN sidebar shows
					// only the Overview stub.
					label: 'Python',
					translations: { az: 'Python Dərsləri' },
					items: [
						{ label: 'Overview', translations: { az: 'Giriş' }, link: '/python/' },
						{
							label: '00 — Start here',
							translations: { az: '00 — Başlanğıc' },
							items: [{ autogenerate: { directory: 'python/00-baslangic' } }],
						},
						{
							label: '01 — Talk to Python',
							translations: { az: '01 — Python ilə danış' },
							items: [{ autogenerate: { directory: 'python/01-python-ile-danis' } }],
						},
						{
							label: '02 — Make decisions',
							translations: { az: '02 — Qərar ver' },
							items: [{ autogenerate: { directory: 'python/02-qerar-ver' } }],
						},
						{
							label: '03 — Repeat',
							translations: { az: '03 — Təkrarla' },
							items: [{ autogenerate: { directory: 'python/03-tekrarla' } }],
						},
						{
							label: '04 — Collections',
							translations: { az: '04 — Kolleksiyalar' },
							items: [{ autogenerate: { directory: 'python/04-kolleksiyalar' } }],
						},
						{
							label: '05 — Functions',
							translations: { az: '05 — Funksiyalar' },
							items: [{ autogenerate: { directory: 'python/05-funksiyalar' } }],
						},
						{
							label: '06 — Projects',
							translations: { az: '06 — Layihə missiyaları' },
							items: [{ autogenerate: { directory: 'python/06-layihe-missiyalari' } }],
						},
						{ label: 'Glossary', translations: { az: 'Sözlük' }, link: '/python/sozluk/' },
					],
				},
				{
					label: 'BrauzerLab',
					items: [{ autogenerate: { directory: 'playwright' } }],
				},
				{
					label: 'Exam Helper',
					translations: { az: 'İmtahan Köməkçisi' },
					items: [{ autogenerate: { directory: 'exam-helper' } }],
				},
				{
					label: 'Projects',
					items: [{ autogenerate: { directory: 'projects' } }],
				},
				{ label: 'About', link: '/about/', translations: { az: 'Haqqında' } },
			],
			// Edit-this-page links — wire up once the repo is on GitHub.
			// editLink: { baseUrl: 'https://github.com/<user>/<repo>/edit/main/' },
		}),
		sitemap({
			// /python-demo/ is an internal M1 verification page — keep it out of the sitemap.
			filter: (page) => !page.includes('/python-demo'),
		}),
	],
});
